import {describe,it,expect} from 'vitest';
import source from '../../src/content/missions.json';
import {validateContent} from '../../src/content/validate';
const fresh=()=>structuredClone(source);
describe('conteúdo e montagens da bancada',()=>{
 it('seis missões com duas montagens funcionais',()=>expect(validateContent(source)).toHaveLength(6));
 it('JSON sem campanha bloqueado',()=>expect(()=>validateContent({})).toThrow(/JSON/));
 it('campo desconhecido bloqueado',()=>expect(()=>validateContent({...source,extra:1})).toThrow(/JSON/));
 it('IDs duplicados bloqueados',()=>{const m=fresh();m.missions[1].id=m.missions[0].id;expect(()=>validateContent(m)).toThrow(/duplicados/);});
 it('ordem é contratual',()=>{const m=fresh();m.missions.reverse();expect(()=>validateContent(m)).toThrow(/Ordem/);});
 it('solução com cabo ausente quebra build',()=>{const m=fresh();m.missions[0].solutions[0].edges.pop();expect(()=>validateContent(m)).toThrow(/Solução/);});
 it('duas soluções não podem ser idênticas',()=>{const m=fresh();m.missions[1].solutions[1]=structuredClone(m.missions[1].solutions[0]);expect(()=>validateContent(m)).toThrow(/diferentes/);});
 it('saída inventada quebra conteúdo',()=>{const m=fresh();m.missions[1].cases[0].expected[0].value=8;expect(()=>validateContent(m)).toThrow(/saídas/);});
 it('meta contador tem origem nas entradas',()=>{const m=fresh();m.missions[5].cases[0].target=9;expect(()=>validateContent(m)).toThrow(/Metas/);});
 it('IDs de pacote são únicos',()=>{const m=fresh();m.missions[2].cases[0].packets[1].id=m.missions[2].cases[0].packets[0].id;expect(()=>validateContent(m)).toThrow(/pacote/);});
 it('cenários precisam de IDs únicos',()=>{const m=fresh();m.missions[1].cases[1].id=m.missions[1].cases[0].id;expect(()=>validateContent(m)).toThrow(/cenário/);});
 it('final exige três lotes',()=>{const m=fresh();m.missions[5].cases.pop();expect(()=>validateContent(m)).toThrow(/três/);});
 it('lotes acima de dez são rejeitados',()=>{const m=fresh();m.missions[0].cases[0].packets=Array.from({length:11},()=>m.missions[0].cases[0].packets[0]);expect(()=>validateContent(m)).toThrow(/JSON/);});
 it('entradas fixas não podem ser processadores',()=>{const m=fresh();m.missions[0].fixed[0].kind='add';expect(()=>validateContent(m)).toThrow(/fixos/);});
});
