import {createGame,stepGame} from '../core/arcade-engine';
import type {GameState,Rules} from '../core/arcade-engine';
import {escape} from './shared';
export interface Player {play:()=>void;pause:()=>void;reset:()=>void;dispose:()=>void;state:()=>GameState;playing:()=>boolean}
export const PLAYER_CSS=`.arcade-screen{background:#060c19;border:1px solid #294353;border-radius:18px;overflow:hidden;position:relative}.arcade-hud{display:flex;justify-content:space-between;padding:14px 18px;color:#e8f4ff;font:700 14px Consolas,monospace;background:#0d1c2b}.arcade-hud strong{color:#f9d65c}.arcade-stage{aspect-ratio:3/2;position:relative}.arcade-stage svg{width:100%;height:100%;display:block}.arcade-message{position:absolute;inset:0;display:grid;place-content:center;text-align:center;background:#030a1588;color:#edf6ff;pointer-events:none;padding:20px;font-family:Trebuchet MS,sans-serif}.arcade-message strong{font-size:28px}.arcade-message small{margin-top:10px}.arcade-controls{display:flex;gap:10px;justify-content:center;padding:12px;background:#0d1c2b}.arcade-controls button{min-height:48px;min-width:65px;border:1px solid #34556d;background:#183447;color:#edf6ff;border-radius:10px;font-size:18px;touch-action:none;cursor:pointer}.arcade-controls button:focus-visible{outline:3px solid #f9d65c}.arcade-controls button:active{background:#31596e}.arcade-legend{display:flex;gap:16px;justify-content:center;font:12px Consolas,monospace;color:#a7bacb;padding:12px 4px}.arcade-stage [data-type=pedra]{color:#ed947b}.arcade-stage [data-type=estrela]{color:#f9d65c}.arcade-stage [data-type=cristal]{color:#64e8e4}`;
function board(s:GameState,reduced:boolean):string{
 const stars=Array.from({length:24},(_,i)=>`<circle cx="${(i*83+31)%480}" cy="${(i*59+17)%320}" r="${i%3===0?1.6:1}" fill="#a1c2e5" opacity="${i%2?.5:.2}"/>`).join('');
 const items=s.items.map(i=>`<g data-item="${i.id}" data-type="${i.type}" data-x="${i.x}" data-y="${i.y}" transform="translate(${i.x} ${i.y})">${i.type==='pedra'?'<path d="M-15-8l10-9 14 4 9 12-4 14-14 5-13-9Z" fill="#533846" stroke="#ed947b" stroke-width="2"/><circle cx="-3" cy="-3" r="4" fill="#342735"/><circle cx="8" cy="7" r="3" fill="#342735"/>':i.type==='estrela'?'<path d="M0-17l5 11 13 1-10 8 3 13L0 9-11 16l3-13-10-8 13-1Z" fill="#f9d65c" stroke="#fff2b6" stroke-width="1.5"/>':'<path d="M0-16l11 7v16L0 16-11 7V-9Z" fill="#286b78" stroke="#64e8e4" stroke-width="2"/><path d="M0-16V16M-11-9L0-2 11-9" fill="none" stroke="#64e8e4"/>'}</g>`).join('');
 return `<svg viewBox="0 0 480 320" role="img" aria-label="Nave em ${Math.round(s.x)}, ${s.score} pontos, ${s.lives} vidas"><defs><linearGradient id="space" x2="0" y2="1"><stop stop-color="#081020"/><stop offset="1" stop-color="#11283b"/></linearGradient></defs><rect width="480" height="320" fill="url(#space)"/>${stars}<path d="M0 295H480" stroke="#295369" stroke-dasharray="3 7"/>${items}<g id="ship" data-x="${s.x}" transform="translate(${s.x} 270)"><path d="M0-21L18 17 0 9-18 17Z" fill="${s.flash==='hit'?'#ed947b':'#edf6ff'}" stroke="#64e8e4" stroke-width="2"/><path d="M0-10L6 4H-6Z" fill="#297483"/><path d="M-5 14L0 ${reduced?24:24+s.tick%5} 5 14" fill="#f9d65c"/></g>${s.flash==='collect'&&!reduced?`<circle cx="${s.x}" cy="270" r="28" fill="none" stroke="#64e8e4"/>`:''}</svg>`;
}
export function mountPlayer(host:HTMLElement,rules:Rules,onEnd:(state:GameState)=>void=()=>{},reduced=()=>false):Player{
 let state=createGame(rules),active=false,timer:ReturnType<typeof setInterval>|undefined;
 const input={left:false,right:false};
 host.innerHTML='<div class="arcade-screen"><div class="arcade-hud"><span>ÓRBITA / <strong id="game-score">0</strong> pts</span><span id="game-lives">♥ ♥ ♥</span><span id="game-wave">ONDA 01</span></div><div class="arcade-stage" id="game-stage"></div><div class="arcade-controls"><button id="move-left" aria-label="Mover nave para esquerda">←</button><button id="pause-game" aria-label="Pausar ou retomar partida">Ⅱ</button><button id="move-right" aria-label="Mover nave para direita">→</button></div></div><div class="arcade-legend"><span>◆ 10 pontos</span><span>✦ 25 pontos</span><span>☄ −1 vida</span></div><p id="game-notice" class="sr-only" aria-live="polite"></p>';
 const stage=host.querySelector<HTMLElement>('#game-stage')!,score=host.querySelector<HTMLElement>('#game-score')!,lives=host.querySelector<HTMLElement>('#game-lives')!,wave=host.querySelector<HTMLElement>('#game-wave')!,notice=host.querySelector<HTMLElement>('#game-notice')!;
 function paint(){stage.dataset.status=state.status;stage.dataset.tick=String(state.tick);stage.innerHTML=board(state,reduced());score.textContent=String(state.score);lives.textContent='♥ '.repeat(Math.max(0,state.lives)).trim()||'SEM VIDAS';wave.textContent=`ONDA ${String(state.wave).padStart(2,'0')}`;
  if(!active||state.status!=='playing'){const title=state.status==='won'?'Você venceu!':state.status==='lost'?'Tente outra vez':state.status==='error'?'Revise a regra':state.tick?'Pausado':'Seu jogo está aqui';const detail=state.status==='error'?state.error:state.status==='won'?'100 pontos alcançados':state.status==='lost'?'Jogar reinicia a partida':state.tick?'Retome pelo botão Ⅱ':'Jogar para testar na prática';stage.innerHTML+=`<div class="arcade-message"><strong>${escape(title)}</strong><small>${escape(detail)}</small></div>`;}
 }
 function pause(){active=false;if(timer)clearInterval(timer);timer=undefined;input.left=input.right=false;paint();}
 function play(){if(state.status!=='playing')state=createGame(rules);if(state.status==='error'){paint();onEnd(state);return;}if(active)return;active=true;paint();timer=setInterval(()=>{const before=state;state=stepGame(state,input,rules);if(state.lives!==before.lives)notice.textContent=`${state.lives} vidas restantes.`;if(state.status!=='playing'){pause();notice.textContent=state.status==='won'?'Partida vencida.':state.error||'Partida encerrada.';onEnd(state);}else paint();},20);}
 const clear=()=>{input.left=input.right=false;};
 const key=(event:KeyboardEvent,down:boolean)=>{const el=event.target as HTMLElement;if(el instanceof HTMLTextAreaElement||el instanceof HTMLInputElement||el instanceof HTMLSelectElement||!active)return;const which=['ArrowLeft','a','A'].includes(event.key)?'left':['ArrowRight','d','D'].includes(event.key)?'right':null;if(which){event.preventDefault();input[which]=down;}if(down&&event.key===' '){event.preventDefault();pause();}};
 const down=(e:KeyboardEvent)=>key(e,true),up=(e:KeyboardEvent)=>key(e,false),visibility=()=>{if(document.hidden)pause();};
 window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',clear);document.addEventListener('visibilitychange',visibility);
 const cleanups:(()=>void)[]=[];
 for(const side of ['left','right'] as const){const button=host.querySelector<HTMLButtonElement>(`#move-${side}`)!;const press=(e:PointerEvent)=>{e.preventDefault();button.setPointerCapture(e.pointerId);input[side]=true;};const release=()=>{input[side]=false;};button.addEventListener('pointerdown',press);button.addEventListener('pointerup',release);button.addEventListener('pointercancel',release);button.addEventListener('lostpointercapture',release);cleanups.push(()=>{button.removeEventListener('pointerdown',press);button.removeEventListener('pointerup',release);button.removeEventListener('pointercancel',release);button.removeEventListener('lostpointercapture',release);});}
 const pauseButton=host.querySelector<HTMLButtonElement>('#pause-game')!,toggle=()=>{if(active)pause();else play();};pauseButton.addEventListener('click',toggle);paint();
 return {play,pause,reset(){pause();state=createGame(rules);paint();},state:()=>structuredClone(state),playing:()=>active,dispose(){pause();window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',clear);document.removeEventListener('visibilitychange',visibility);pauseButton.removeEventListener('click',toggle);cleanups.forEach(f=>f());}};
}
