import type {Case,CircuitState,Layout,Mission,Node,Packet} from '../core/circuit-types';
import {cablePath} from '../core/circuit-layout';
import {escape} from './shared';
export const names:Record<Node['kind'],string>={source:'Entrada',sink:'Destino',relay:'Ponte',add:'Somar',multiply:'Multiplicar',filter:'Sensor',buffer:'Memória'};
export const sensorNames={valid:'Íntegro',permission:'Autorizado',credentials:'Credencial',energy:'Energia',maintenance:'Manutenção',countMet:'Meta atingida',batchDone:'Lote completo'};
export const sensorIcons={valid:'✓',permission:'⊕',credentials:'⚿',energy:'ϟ',maintenance:'⚒',countMet:'#',batchDone:'▤'};
export function symbol(n:Node):string{return n.kind==='source'?'▸':n.kind==='sink'?n.id==='ok'?'↥':'↺':n.kind==='relay'?'↗':n.kind==='add'?`+${n.config.value}`:n.kind==='multiply'?`×${n.config.value}`:n.kind==='buffer'?'▤':'◇';}
export function formula(n:Node):string{const c=n.config;if(n.kind!=='filter')return '';let t=sensorIcons[c.a!];if(c.op!=='single')t+=` ${c.op==='and'?'∧':'∨'} ${sensorIcons[c.b!]}`;if(c.third)t=`(${t}) ${c.outer==='and'?'∧':'∨'} ${sensorIcons[c.c!]}`;return c.invert?`¬(${t})`:t;}
function attributes(m:Mission,p:Packet):string{
 if(m.mode==='boolean')return `<small aria-label="credencial ${p.credentials?'sim':'não'}, energia ${p.energy?'sim':'não'}, manutenção ${p.maintenance?'sim':'não'}">${p.credentials?'⚿':'·'} ${p.energy?'ϟ':'·'} ${p.maintenance?'⚒':'·'}</small>`;
 if(['filter','buffer','final'].includes(m.mode))return `<small aria-label="${p.valid?'íntegro':'corrompido'}, ${p.permission?'autorizado':'sem autorização'}">${p.valid?'✓':'×'}${m.mode==='final'?p.permission?' ⊕':' ⊖':''}</small>`;
 return '';
}
export function packets(m:Mission,c:Case,s?:CircuitState):string{return `<div class="packet-strip" aria-label="Entradas e metas">${c.packets.map(p=>{const goal=c.expected.find(o=>o.id===p.id)!,out=s?.outputs.find(o=>o.id===p.id),done=out&&out.sink===goal.sink&&out.value===goal.value;return `<div class="packet-card ${done?'delivered':''} ${s?.lastPacket?.id===p.id?'current':''}" aria-label="${escape(p.id)}: entrada ${p.value}, meta ${goal.value} no ${goal.sink==='ok'?'servidor':'revisão'}"><span>${escape(p.id)}</span><strong>${p.value}<i>→</i>${goal.sink==='ok'?goal.value:'↺'}</strong>${attributes(m,p)}${done?'<b>✓</b>':''}</div>`;}).join('')}</div>`;}
export function board(m:Mission,l:Layout,s:CircuitState|undefined,selected:string,armed:boolean,target:number):string{
 const pos=(n:{x:number;y:number})=>[n.x*100+50,n.y*100+50];
 const wires=l.edges.map(e=>{const a=l.nodes.find(n=>n.id===e.from)!,b=l.nodes.find(n=>n.id===e.to)!,path=cablePath(m,a,b),last=s?.lastEdge?.from===e.from&&s.lastEdge.port===e.port,invalid=!path;const points=(path??[a,b]).map(p=>pos(p).join(',')).join(' ');return `<polyline points="${points}" class="wire ${e.port} ${last?'lit':''} ${invalid?'invalid':''}" marker-end="url(#arrow-${e.port})"/>`;}).join('');
 let token='';if(s?.lastPacket&&s.active){const n=l.nodes.find(n=>n.id===s.active)!;const [x,y]=pos(n),a=s.lastEdge?l.nodes.find(n=>n.id===s.lastEdge!.from):undefined,route=a?cablePath(m,a,n):null;token=`<g class="packet-token ${s.status==='failed'?'bad':''}" transform="translate(${x} ${y})">${route&&s.status==='running'?`<animateTransform attributeName="transform" type="translate" values="${route.map(p=>pos(p).join(' ')).join(';')}" dur=".16s" fill="freeze"/>`:''}<circle r="17"/><text y="5" text-anchor="middle">${s.lastPacket.value}</text></g>`;}
 const slots=Array.from({length:35},(_,i)=>{const x=i%7,y=Math.floor(i/7),n=l.nodes.find(n=>n.x===x&&n.y===y),blocked=m.blocked.some(p=>p.x===x&&p.y===y),fixed=n&&m.fixed.some(f=>f.id===n.id),mark=n?.kind==='sink'?s?.outputs.filter(o=>o.sink===n.id).length:undefined;return `<button id="slot-${x}-${y}" class="slot ${n?'filled '+n.kind:'empty'} ${selected===n?.id?'selected':''} ${s?.active===n?.id?'active':''} ${s?.fault===n?.id?'fault':''} ${armed&&!blocked?'targetable':''} ${blocked?'blocked':''}" data-action="slot" data-x="${x}" data-y="${y}" data-node="${n?.id??''}" ${blocked?'disabled':''} draggable="${n&&!fixed?'true':'false'}" aria-label="Encaixe ${x+1}, ${y+1}${n?`: ${names[n.kind]} ${n.kind==='sink'?n.id==='ok'?'servidor':'revisão':n.kind==='add'||n.kind==='multiply'?n.config.value??'':''}${n.kind==='filter'?`, ${formula(n)}`:''}`:blocked?', danificado':', vazio'}"><span class="socket-dot"></span>${n?`<span class="piece-icon ${n.kind==='relay'?'oriented':''}" style="--rotation:${n.rotation*90}deg">${symbol(n)}</span><small>${n.kind==='sink'?n.id==='ok'?'ENVIO':'REVISÃO':n.kind==='source'?'ENTRADA':n.kind==='filter'?formula(n):n.kind==='buffer'?`${s?.count??0} / ${target}`:''}</small>${n.kind!=='sink'?'<i class="port-light"></i>':''}${mark!==undefined?`<b class="sink-count">${mark}</b>`:''}`:blocked?'<span class="broken-mark">╳</span>':'<span class="empty-mark">＋</span>'}</button>`;}).join('');
 return `<div class="circuit-board" aria-label="Bancada de montagem"><svg class="cables" viewBox="0 0 700 500" aria-hidden="true"><defs>${['out','yes','no'].map(p=>`<marker id="arrow-${p}" markerWidth="7" markerHeight="7" refX="6" refY="3" orient="auto"><path d="M0 0L6 3L0 6" class="arrow ${p}"/></marker>`).join('')}</defs>${wires}</svg><div class="socket-grid">${slots}</div><svg class="tokens" viewBox="0 0 700 500" aria-hidden="true">${token}</svg></div>`;
}
