import type {Kind,Mission,Node} from '../core/circuit-types';
import {ports} from '../core/circuit-layout';
import {names,sensorNames,symbol} from './circuit-board';
export function palette(m:Mission,armed:Kind|null):string{return `<div class="piece-tray" aria-label="Peças disponíveis">${m.available.map(kind=>`<button id="piece-${kind}" data-action="pick" data-kind="${kind}" draggable="true" class="tray-piece ${armed===kind?'picked':''}" aria-label="Escolher ${names[kind]}"><span>${symbol({kind,config:{value:kind==='multiply'?2:1}} as Node)}</span><small>${names[kind]}</small></button>`).join('')}</div>`;}
export function inspector(m:Mission,n:Node,connecting:string):string{
 const fixed=m.fixed.some(f=>f.id===n.id);return `<div class="inspector"><strong>${n.kind==='sink'?n.id==='ok'?'Servidor':'Revisão':names[n.kind]}</strong><div class="port-controls">${ports(n).map(port=>`<button id="connect-${port}" data-action="connect" data-port="${port}" data-from="${n.id}" draggable="true" class="${connecting===port?'picked':''}" aria-label="Conectar saída ${port==='yes'?'SIM':port==='no'?'NÃO':'principal'}">${port==='yes'?'✓ SIM':port==='no'?'× NÃO':'↗ Conectar'}</button>`).join('')}</div>${!fixed?`<div class="piece-tools">${['add','multiply','filter'].includes(n.kind)?'<button id="configure-piece" data-action="configure" aria-label="Configurar peça">⚙</button>':''}<button id="rotate-piece" data-action="rotate" aria-label="Girar peça">↻</button><button id="move-piece" data-action="move" aria-label="Mover peça">↔</button><button id="remove-piece" data-action="remove" aria-label="Remover peça">×</button></div>`:''}<button id="disconnect-piece" data-action="disconnect" aria-label="Soltar cabos de saída">⤬</button><button id="close-inspector" data-action="deselect" aria-label="Fechar seleção">＋ Peças</button></div>`;
}
export function configuration(m:Mission,n:Node):string{
 if(n.kind!=='filter')return `<h2>${names[n.kind]}</h2><p>A peça transforma cada número que passa.</p><div class="value-picker">${m.parameters[n.kind as 'add'|'multiply'].map(value=>`<button data-action="value" data-value="${value}" class="${n.config.value===value?'picked':''}" aria-label="Valor ${value}">${n.kind==='add'?'+':'×'}${value}</button>`).join('')}</div>`;
 const c=n.config;
 const select=(id:string,label:string,value:string,options:[string,string][])=>`<label>${label}<select id="${id}" data-change="config" data-key="${id.replace('config-','')}">${options.map(([v,t])=>`<option value="${v}" ${value===v?'selected':''}>${t}</option>`).join('')}</select></label>`;
 const predicates=m.predicates.map(p=>[p,sensorNames[p]] as [string,string]);
 return `<h2>Sensor de decisão</h2><div class="sensor-diagram"><span>ENTRADA</span><strong>◇</strong><span class="yes">✓ SIM</span><span class="no">× NÃO</span></div><div class="rule-fields">${select('config-a','Quando…',c.a!,predicates)}${select('config-op','Combine',c.op!,[['single','Um sensor'],['and','E — os dois'],['or','OU — pelo menos um']])}${c.op!=='single'?select('config-b','Com…',c.b!,predicates):''}<label class="check-field"><input id="config-third" type="checkbox" data-change="config" data-key="third" ${c.third?'checked':''}> Acrescentar outro sensor</label>${c.third?select('config-outer','Combine o grupo',c.outer!,[['and','E'],['or','OU']])+select('config-c','Com…',c.c!,predicates):''}<label class="check-field"><input id="config-invert" type="checkbox" data-change="config" data-key="invert" ${c.invert?'checked':''}> Inverter SIM / NÃO</label></div>`;
}

