import type {LabState,Mission,Scenario} from '../core/lab-types';
import {escape,robot} from './shared';
export function scenarioSummary(m:Mission,s:Scenario):string{
 if(m.mode==='variables')return `Inicial ${s.energy} · carga +${s.charge} · custo ${s.cost} · alvo ${s.targetEnergy}`;
 if(m.mode==='boolean')return `Credencial ${s.credentials?'válida':'inválida'} · energia ${s.energy} · manutenção ${s.maintenance?'autorizada':'não'}`;
 if(s.packets.length)return `${s.packets.length} pacote(s) · meta de enviados ${s.targetCount}`;
 return 'Central → sensor → leitura → comunicação';
}
function device(label:string,on:boolean,value:string):string{return `<div class="device ${on?'online':''}"><span class="device-light"></span><small>${label}</small><strong>${value}</strong><span>${on?'PRONTO':'AGUARDANDO'}</span></div>`;}
export function labBoard(m:Mission,s:Scenario,state:LabState|undefined):string{
 const energy=state?.energy??s.energy,count=state?.count;
 let body:string;
 if(m.mode==='sequence')body=`<div class="central-layout">${device('01 / CENTRAL',!!state?.powered,state?.powered?'Ligada':'Desligada')}<b>→</b>${device('02 / SENSOR',!!state?.sensorOn,state?.sensorOn?'Ativo':'Inativo')}<b>↓</b>${device('03 / LEITURA',state?.reading!==undefined&&state.reading!==null,state?.reading!==undefined&&state.reading!==null?`${state.reading} °C`:'Sem leitura')}<b>→</b>${device('04 / ENVIO',!!state?.reported,state?.reported?'Enviado':'Pendente')}</div>`;
 else if(m.mode==='variables')body=`<div class="energy-machine"><span class="machine-symbol">ϟ</span><span class="energy-label">VARIÁVEL / energia</span><strong data-testid="energy">${energy}</strong><div class="battery-track"><i style="width:${Math.min(100,energy*14)}%"></i></div><div class="machine-values"><span>CARGA <b>+${s.charge}</b><small>${state?.charges?0:1} disponível</small></span><span>OPERAÇÃO <b>−${s.cost}</b><small>${state?.operations??0} / 2 feitas</small></span><span>ALVO <b>${s.targetEnergy}</b><small>energia final</small></span></div></div>`;
 else if(m.mode==='boolean')body=`<div class="access-machine"><div class="access-inputs">${device('CREDENCIAL',s.credentials,s.credentials?'Válida':'Inválida')}${device('ENERGIA ≥ 3',energy>=3,energy>=3?'Sim':'Não')}${device('MANUTENÇÃO',s.maintenance,s.maintenance?'Autorizada':'Não')}</div><div class="access-door ${state?.decision?'opened':''}"><span>${state?.decision===null||state?.decision===undefined?'◇':state.decision?'✓':'▣'}</span><strong data-testid="decision">${state?.decision===null||state?.decision===undefined?'Aguardando regra':state.decision?'ACESSO LIBERADO':'ACESSO NEGADO'}</strong></div></div>`;
 else body=`${m.mode==='final'?`<div class="final-hud"><span class="${state?.powered?'online-text':''}">ϟ CENTRAL ${state?.powered?'LIGADA':'DESLIGADA'}</span><span>${state?.released?'✓ RELATÓRIO LIBERADO':'▣ RELATÓRIO BLOQUEADO'}</span></div>`:''}<div class="packet-feed">${s.packets.map((p,i)=>`<div class="packet ${state?.current===i?'current':''} ${state?.routes[p.id]?'processed':''}"><span class="packet-icon">▤</span><strong>${escape(p.id)}</strong><span class="packet-condition">${p.valid?'✓ Íntegro':'! Corrompido'}${m.mode==='final'?`<br>${p.permission?'✓ Autorizado':'! Sem permissão'}`:''}</span><span class="packet-route">${state?.routes[p.id]==='send'?'→ Enviado':state?.routes[p.id]==='review'?'↘ Revisão':'Aguardando'}</span></div>`).join('')}</div><div class="output-ports"><div><span>ENVIADOS</span><strong>${Object.values(state?.routes??{}).filter(x=>x==='send').length}</strong></div><div><span>EM REVISÃO</span><strong>${Object.values(state?.routes??{}).filter(x=>x==='review').length}</strong></div>${m.hasLoop?`<div class="counter-port"><span>VARIÁVEL / enviados</span><strong data-testid="count">${count??'—'}</strong><small>meta ${s.targetCount} · ${state?.lotDone?'lote concluído':'lote em espera'}</small></div>`:''}</div>`;
 const last=state?.trace.at(-1);
 return `<section class="simulator" aria-labelledby="system-title"><div class="panel-heading"><h2 id="system-title">Sistema em ação</h2><span class="live-chip">${state?.status==='won'?'✓ RESOLVIDO':state?.status==='failed'?'! REVISAR':'● LAB ONLINE'}</span></div><p class="scenario-description">${escape(scenarioSummary(m,s))}</p><div class="system-stage">${body}</div><div class="operator-strip"><div>${robot}</div><p data-testid="feedback" role="status" aria-live="polite">${escape(state?.message??'O sistema está pronto. Construa seu programa e veja cada instrução alterar o resultado.')}</p></div>${last&&m.mode!=='sequence'&&m.mode!=='boolean'?`<div class="state-change"><span>ÚLTIMA MUDANÇA</span><strong>${m.mode==='variables'?`energia: ${last.before.energy} → ${last.after.energy}`:`enviados: ${last.before.count??'—'} → ${last.after.count??'—'}`}</strong></div>`:''}</section>`;
}
export function traceView(state:LabState|undefined):string{return `<details class="execution-trace" ${state?.status==='failed'?'open':''}><summary>Registro das instruções · ${state?.steps??0} passos</summary><ol>${state?.trace.map(t=>`<li><span>${escape(t.path.split('.')[0])}</span>${escape(t.message)}</li>`).join('')??''}</ol></details>`;}
