import { countBlocks } from '../core/engine';
import type { Command, Primitive, Level, RunState } from '../core/types';
import { escape } from './shared';
export const labels:Record<Primitive,string>={advance:'Avançar',left:'Virar à esquerda',right:'Virar à direita'};
export const icons:Record<Primitive,string>={advance:'↑',left:'↶',right:'↷'};
export function editor(level:Level,program:Command[],active:boolean,state:RunState|undefined,draft:Primitive[],times:number):string {
  const commandIndex=state?.cursor ? state.executions[state.cursor-1]?.commandIndex : -1;
  const disabled=active?'disabled':'';
  const basic=Object.entries(labels).map(([kind,label])=>`<button id="add-${kind}" data-action="add" data-kind="${kind}" ${disabled}><span class="command-icon">${icons[kind as Primitive]}</span>${label}</button>`).join('');
  const rows=program.map((command,i)=>`<li class="program-row ${i===commandIndex?'current':''}"><span class="line-no">${String(i+1).padStart(2,'0')}</span><div class="command-label">${command.kind==='repeat'?`<strong>Repetir ${command.times} vezes</strong><span class="repeat-body">${command.body.map((kind)=>escape(labels[kind])).join(' → ')}</span>`:escape(labels[command.kind])}</div><div class="line-controls"><button aria-label="Mover comando ${i+1} para cima" data-action="up" data-index="${i}" ${active||i===0?'disabled':''}>↑</button><button aria-label="Mover comando ${i+1} para baixo" data-action="down" data-index="${i}" ${active||i===program.length-1?'disabled':''}>↓</button><button aria-label="Remover comando ${i+1}" data-action="remove" data-index="${i}" ${disabled}>×</button></div></li>`).join('');
  const repeat=level.allowRepeat?`<details class="repeat-builder" ${draft.length?'open':''}><summary>Montar bloco repetir</summary><p>Escolha as ações do grupo. O grupo não pode conter outra repetição.</p><div class="draft-controls">${Object.entries(labels).map(([kind,label])=>`<button data-action="draft" data-kind="${kind}" ${disabled}>${label}</button>`).join('')}</div><p class="draft" aria-live="polite">${draft.length?draft.map((kind)=>labels[kind]).join(' → '):'Grupo vazio: adicione uma ação.'}</p><div class="repeat-footer"><label for="repeat-times">Vezes</label><select id="repeat-times" ${disabled}>${[2,3,4].map((n)=>`<option ${times===n?'selected':''}>${n}</option>`).join('')}</select><button data-action="draft-clear" ${disabled}>Limpar grupo</button><button class="primary" data-action="repeat-add" ${active||!draft.length?'disabled':''}>Adicionar repetição</button></div></details>`:'';
  return `<section class="editor" aria-labelledby="editor-title"><div class="section-heading"><h2 id="editor-title">Seu programa</h2><span data-testid="block-count">${countBlocks(program)} / ${level.maxBlocks} blocos</span></div><div class="palette">${basic}</div>${repeat}<ol class="program" aria-label="Sequência de comandos">${rows||'<li class="empty-program">O robô espera suas instruções.<br>Adicione os comandos acima.</li>'}</ol><div class="execution-controls"><button id="run" class="primary" data-action="run" ${active?'disabled':''}>▶ Executar</button><button id="step" data-action="step" ${active?'disabled':''}>Um passo</button><button id="stop" data-action="stop" ${active?'':'disabled'}>Parar</button><button id="clear" data-action="clear" ${disabled}>Limpar</button></div><p class="editor-note">Virar muda a direção, sem avançar. Você pode editar e tentar quantas vezes quiser.</p></section>`;
}
