import type {Block,LabState,Mission,Scenario} from '../core/lab-types';
import {escape,robot} from './shared';
import {editor} from './lab-editor';
import {labBoard,scenarioSummary,traceView} from './lab-board';
import type {Preferences} from '../core/preferences';
export interface Campaign {completed:string[];saved:boolean;legacy:boolean;version:{version:string;sha:string}}
export type Stage='demo'|'practice'|'challenge';
export type Overlay='pause'|'options'|'help'|'new'|'reset'|null;
export const xp=(missions:Mission[],c:Campaign)=>missions.reduce((n,m)=>n+(c.completed.includes(m.id)?m.reward:0),0);
export function header(missions:Mission[],c:Campaign,workspace=false):string{return `<header class="game-header"><button class="brand" data-action="${workspace?'pause':'home'}"><span class="brand-mark">↱</span><span>ROTA DO CÓDIGO<small>LABORATÓRIO DE LÓGICA</small></span></button><div class="campaign-meter"><strong data-testid="xp">${xp(missions,c)} XP</strong><div class="xp-track"><i style="width:${xp(missions,c)/7}%"></i></div><span>${c.completed.length}/6 SETORES</span></div><button id="top-menu" class="quiet" data-action="${workspace?'pause':'home'}">${workspace?'Ⅱ Pausar':'Menu principal'}</button></header>`;}
export function home(missions:Mission[],c:Campaign):string{return `<main class="title-screen"><div class="title-copy"><p class="eyebrow"><span class="status-led"></span> SISTEMA RDC / CONEXÃO ESTABELECIDA</p><h1>ROTA DO<br><em>CÓDIGO</em><span>O laboratório de lógica</span></h1><p class="title-description">O núcleo parou. Aprenda a criar regras, tomar decisões e devolver energia ao sistema.</p><nav class="main-menu" aria-label="Menu do jogo"><button id="continue-game" class="${c.completed.length?'primary':'quiet'}" data-action="continue" ${c.completed.length?'':'disabled'}><span>▶</span> Continuar <small>${c.completed.length===6?'Campanha concluída':c.completed.length?`Setor ${c.completed.length+1}`:'Nenhum progresso'}</small></button><button id="new-game" class="${c.completed.length?'quiet':'primary'}" data-action="new"><span>＋</span> Novo jogo <small>Comece pelo setor 01</small></button><button id="missions-menu" data-action="missions"><span>▦</span> Missões <small>5 missões + desafio final</small></button><button id="how-to" data-action="help"><span>?</span> Como jogar</button><button id="options" data-action="options"><span>⚙</span> Opções</button></nav><p class="version">v${escape(c.version.version)} · ${escape(c.version.sha.slice(0,7))} <span>WEB / OFFLINE</span></p></div><div class="title-scene"><div class="orbital-grid"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><span class="scene-node node-a">SE</span><span class="scene-node node-b">E / OU</span><span class="scene-node node-c">↻</span><div class="hero-robot">${robot}</div></div><div class="terminal-badge"><span>UNIDADE RDC-01</span><strong>AGUARDANDO SEU PROGRAMA</strong><small>ORDEM · MEMÓRIA · DECISÕES · REPETIÇÃO</small></div></div><div class="title-footer"><span>${c.saved?'Progresso local neste navegador':'Progresso apenas nesta sessão'}</span><span>SEM CONTA · SEM CRONÔMETRO</span></div>${c.legacy?'<p class="legacy-note">Nova campanha de lógica: o progresso das rotas anteriores foi preservado e não desbloqueia estes desafios.</p>':''}</main>`;}
export function campaign(missions:Mission[],c:Campaign):string{return `<main class="sector-screen"><div class="sector-heading"><p class="eyebrow">MAPA DO LABORATÓRIO</p><h1>Cinco sistemas.<br><em>Um núcleo para recuperar.</em></h1><p>Cada setor ensina uma ferramenta. O final reúne tudo que você praticou.</p></div><div class="sector-map">${missions.map((m,i)=>{const done=c.completed.includes(m.id),locked=i>c.completed.length;return `<button class="sector ${i===5?'final-sector':''} ${done?'done':''} ${locked?'locked':'available'}" data-action="select" data-index="${i}" ${locked?'disabled':''} aria-label="${i===5?'Desafio final':`Missão ${i+1}`}: ${escape(m.title)}${locked?', bloqueada':done?', concluída':', disponível'}"><span class="sector-top">${i===5?'NÚCLEO FINAL':`SETOR 0${i+1}`} <b>${done?'✓':locked?'▣':'▶'}</b></span><span class="sector-symbol">${m.icon}</span><h2>${escape(m.title)}</h2><p>${escape(m.concept)}</p><span class="sector-bottom">${done?'MEDALHA CONQUISTADA':locked?'CONCLUA O SETOR ANTERIOR':'ENTRAR NO SETOR'}<strong>+${m.reward} XP</strong></span></button>`;}).join('')}</div><div class="sector-bottom-note"><span>${c.completed.length}/6 setores recuperados · ${xp(missions,c)}/700 XP</span><button data-action="home">Voltar ao menu</button></div></main>`;}
export function lesson(m:Mission,index:number,review=false):string{return `<main class="lesson-screen"><div class="lesson-heading"><p class="eyebrow">${index===5?'DESAFIO FINAL':`MISSÃO 0${index+1}`} / APRENDA ANTES DE PROGRAMAR</p><h1>${escape(m.title)}</h1><p>${escape(m.brief)}</p></div><div class="learning-path"><span class="active">01 ENTENDA</span><span>02 VEJA O EXEMPLO</span><span>03 PRATIQUE</span><span>04 DESAFIE-SE</span></div><div class="lesson-cards">${m.lessons.map((l,i)=>`<article><span class="lesson-number">0${i+1}</span><h2>${escape(l.title)}</h2><p>${escape(l.text)}</p></article>`).join('')}</div><div class="mission-objective"><span>NA PRÁTICA, VOCÊ VAI…</span><p>${escape(m.goal)}</p></div><div class="lesson-actions"><button id="lesson-next" class="primary large" data-action="${review?'return-work':'demo'}">${review?'Voltar ao meu programa':'Ver exemplo interativo →'}</button><button data-action="missions">Mapa de missões</button></div></main>`;}
export function workspace(m:Mission,index:number,stage:Stage,program:Block[],cases:Scenario[],caseIndex:number,state:LabState|undefined,results:('pending'|'won'|'failed')[],busy:boolean,hintCount:number,error:string):string{
 const demo=stage==='demo',s=cases[caseIndex];
 return `<main class="workspace"><div class="workspace-heading"><div><p class="eyebrow">${index===5?'NÚCLEO FINAL':`SETOR 0${index+1}`} / ${demo?'EXEMPLO INTERATIVO':stage==='practice'?'PRÁTICA GUIADA · SEM XP':'DESAFIO INDEPENDENTE'}</p><h1>${escape(m.title)}</h1><p><span class="objective-label">OBJETIVO</span>${escape(m.goal)}</p></div><button id="review-lesson" class="quiet" data-action="review-lesson">↶ Rever explicação</button></div>
 <div class="case-strip" aria-label="Cenários de teste">${cases.map((c,i)=>`<button class="case-chip ${i===caseIndex?'selected':''} ${results[i]}" data-action="case" data-index="${i}" ${busy?'disabled':''} aria-label="Cenário ${i+1}: ${escape(c.label)}"><span>${results[i]==='won'?'✓':results[i]==='failed'?'!':`${i+1}`}</span>${escape(c.label)}</button>`).join('')}<strong data-testid="case-count">${results.filter(x=>x==='won').length}/${cases.length} resolvidos</strong></div>
 ${stage==='practice'?`<div class="practice-coach"><span>?</span><p>${escape(m.hints[0])} O programa inicial é só um começo; complete as regras.</p></div>`:''}
 <div class="work-grid"><div class="system-column">${labBoard(m,s,state)}${traceView(state)}<div class="hints"><button id="hint" data-action="hint">? Preciso de uma dica <span>${hintCount}/3</span></button>${hintCount?`<p>${escape(m.hints[Math.min(hintCount,3)-1])}</p>`:''}</div></div><div class="editor-column">${demo?`<section class="demo-program"><p class="eyebrow">UM EXEMPLO, POR PASSO</p><h2>Observe as instruções</h2><p>Este programa usa dados diferentes do desafio. Execute e acompanhe o sistema.</p>${editor(m,program,state?.activePath??'',true)}</section>`:editor(m,program,state?.activePath??'',busy)}<div class="execution-controls"><button id="run-program" class="primary" data-action="run" ${busy||state?.status==='won'&&demo?'disabled':''}>▶ ${demo?'Executar exemplo':'Testar programa'}</button><button id="step-program" data-action="step" ${busy||state?.status==='won'&&demo?'disabled':''}>Um passo</button><button id="stop-program" class="quiet" data-action="stop" ${busy?'':'disabled'}>Parar</button></div><p class="run-note">${demo?'Exemplo não concede XP.':`O mesmo programa precisa resolver ${cases.length} cenário(s). Os dados estão disponíveis acima.`}</p>${error?`<p class="validation-error" role="alert">${escape(error)}</p>`:''}${demo?`<button id="start-practice" class="primary large next-stage" data-action="practice" ${state?.status==='won'?'':'disabled'}>Agora pratique →</button>`:''}</div></div>
 <div class="mobile-execution"><button id="mobile-run" class="primary" data-action="run" ${busy||state?.status==='won'&&demo?'disabled':''}>▶ ${demo?'Exemplo':'Testar'}</button><button id="mobile-step" data-action="step" ${busy||state?.status==='won'&&demo?'disabled':''}>Um passo</button><button data-action="pause">Ⅱ</button></div></main>`;
}
export function result(m:Mission,stage:Stage,state:LabState,cases:Scenario[],results:('pending'|'won'|'failed')[],earned:number):string{
 const won=results.every(r=>r==='won');return `<main class="result-screen"><div class="result-symbol ${won?'won':'failed'}">${won?'✓':'↶'}</div><p class="eyebrow">${stage==='practice'?'PRÁTICA GUIADA':m.mode==='final'?'DESAFIO FINAL':'RESULTADO DA MISSÃO'}</p><h1>${won?stage==='practice'?'Você entendeu a ferramenta!':'Sistema recuperado!':'Vamos revisar a lógica.'}</h1><p class="result-feedback" role="status" data-testid="feedback">${escape(state.message)}</p><div class="result-cases">${cases.map((s,i)=>`<span class="${results[i]}">${results[i]==='won'?'✓':results[i]==='failed'?'!':'○'} ${escape(s.label)}</span>`).join('')}</div>${won?`<div class="reward-box"><span>${m.icon}</span><div><strong>${stage==='practice'?'PRÁTICA CONCLUÍDA · SEM XP':earned?`+${earned} XP`:'MISSÃO REVISITADA · XP JÁ RECEBIDO'}</strong><p>${stage==='practice'?'Agora resolva casos novos sem o programa inicial.':`Medalha de ${escape(m.concept)} conquistada.`}</p></div></div><p class="result-lesson">${escape(m.lessons.at(-1)!.text)}</p>`:`<div class="diagnostic-box"><strong>O que aconteceu?</strong><p>Confira os dados do cenário e o registro. Seu programa foi preservado: ajuste a instrução, o ramo ou a ordem que causou a falha.</p></div>${traceView(state)}`}<div class="result-actions">${won?`<button id="result-next" class="primary large" data-action="${stage==='practice'?'challenge':'next'}">${stage==='practice'?'Começar desafio →':m.mode==='final'?'Ver laboratório recuperado':'Próxima missão →'}</button>`:''}<button id="edit-program" data-action="edit">${won?'Experimentar outra solução':'Editar e tentar novamente'}</button><button data-action="missions">Mapa de missões</button></div></main>`;
}
export function complete(missions:Mission[],c:Campaign):string{return `<main class="completion-screen"><div class="completion-robot">${robot}</div><p class="eyebrow">NÚCLEO RECUPERADO / CAMPANHA CONCLUÍDA</p><h1>Suas regras.<br><em>Um sistema funcionando.</em></h1><p>Você usou sequência, memória, decisões e repetição em cenários diferentes.</p><strong class="total-xp">${xp(missions,c)} XP</strong><div class="medal-shelf">${missions.map(m=>`<div><span>${m.icon}</span><strong>${escape(m.concept)}</strong></div>`).join('')}</div><div class="result-actions"><button class="primary" data-action="missions">Revisitar missões</button><button data-action="home">Menu principal</button></div></main>`;}
export function modal(overlay:Overlay,preferences:Preferences):string{
 if(!overlay)return '';const body=overlay==='pause'?`<p class="eyebrow">EXECUÇÃO PAUSADA</p><h2>Faça uma pausa.</h2><div class="modal-menu"><button id="resume" class="primary" data-action="resume">▶ Retomar</button><button data-action="review-lesson">Rever explicação</button><button data-action="restart">Reiniciar tentativa</button><button data-action="options">Opções</button><button data-action="missions">Mapa de missões</button></div>`:overlay==='options'?`<p class="eyebrow">OPÇÕES DO JOGO</p><h2>Do seu jeito.</h2><label class="setting"><span>Movimento reduzido<small>Transições e execução mais rápidas; respeita também o sistema.</small></span><input id="setting-reduced" type="checkbox" ${preferences.reduced?'checked':''} data-change="setting" data-key="reduced"></label><label class="setting"><span>Texto maior<small>Aumenta o texto das instruções e controles.</small></span><input id="setting-large" type="checkbox" ${preferences.largeText?'checked':''} data-change="setting" data-key="largeText"></label><button id="reset-progress" class="quiet danger" data-action="reset-prompt">Reiniciar progresso da campanha</button><button class="primary" data-action="close-modal">Voltar</button>`:overlay==='help'?`<p class="eyebrow">COMO JOGAR</p><h2>Aprenda. Programe. Teste.</h2><ol class="help-list"><li>Leia a explicação e execute o exemplo.</li><li>Complete a prática guiada, sem XP.</li><li>No desafio, monte seu programa com blocos em português.</li><li>Use Testar programa ou Um passo para ver variáveis e decisões.</li><li>Corrija o programa até resolver todos os cenários. Ganhe a medalha e libere o próximo setor.</li></ol><p>Teclado e toque funcionam. Não é preciso arrastar, saber uma linguagem ou correr contra o relógio.</p><button class="primary" data-action="close-modal">Entendi</button>`:`<p class="eyebrow">${overlay==='new'?'NOVO JOGO':'REINICIAR CAMPANHA'}</p><h2>Começar novamente?</h2><p>Isso reinicia somente as missões, medalhas e XP desta campanha de lógica. Opções e outros dados do navegador são preservados.</p><div class="result-actions"><button id="reset-cancel" data-action="close-modal">Cancelar</button><button id="reset-confirm" class="primary" data-action="confirm-reset">Confirmar</button></div>`;
 return `<dialog id="game-modal" aria-label="${overlay==='pause'?'Menu de pausa':overlay==='options'?'Opções':overlay==='help'?'Como jogar':'Confirmar reinício'}">${body}</dialog>`;
}
export function caseCaption(m:Mission,s:Scenario):string{return scenarioSummary(m,s);}
