import type {Case,CircuitState,Kind,Layout,Mission} from '../core/circuit-types';
import type {Preferences} from '../core/preferences';
import {escape,robot} from './shared';
import {board,packets} from './circuit-board';
import {configuration,inspector,palette} from './circuit-inspector';
export interface Campaign {completed:string[];saved:boolean;legacy:boolean;version:{version:string;sha:string}}
export type Overlay='pause'|'options'|'help'|'new'|'reset'|'configure'|'cases'|'log'|null;
export const xp=(missions:Mission[],c:Campaign)=>missions.reduce((v,m)=>v+(c.completed.includes(m.id)?m.reward:0),0);
export function header(c:Campaign,inGame=false):string{return `<header class="game-header"><button class="brand" data-action="${inGame?'pause':'home'}" aria-label="${inGame?'Pausar e abrir menu':'Menu principal'}"><span class="brand-mark">↱</span><span>ROTA DO CÓDIGO<small>BANCADA DIGITAL</small></span></button>${inGame?'<button id="top-menu" class="icon-button" data-action="pause" aria-label="Pausar">Ⅱ</button>':`<span class="menu-progress">${c.completed.length}/6 <b>SETORES</b></span>`}</header>`;}
export function home(ms:Mission[],c:Campaign):string{return `<main class="title-screen"><div class="title-copy"><p class="eyebrow">SISTEMA RDC / OFFLINE READY</p><h1>ROTA DO<br><em>CÓDIGO</em></h1><p class="title-description">Construa. Conecte. Faça funcionar.</p><nav class="main-menu" aria-label="Menu do jogo"><button id="continue-game" class="${c.completed.length?'primary':''}" data-action="continue" ${c.completed.length?'':'disabled'}>▶ Continuar</button><button id="new-game" class="${c.completed.length?'':'primary'}" data-action="new">＋ Novo jogo</button><button id="missions-menu" data-action="missions">▦ Missões</button><button id="options" data-action="options">⚙ Opções</button></nav><p class="version">v${escape(c.version.version)} · ${c.version.sha.slice(0,7)} <span>WEB / OFFLINE</span></p></div><div class="title-scene"><div class="orbit"></div><div class="hero-robot">${robot}</div><span class="floating-piece p-one">+1</span><span class="floating-piece p-two">◇</span><span class="floating-piece p-three">▤</span><p>UMA IDEIA.<br><strong>MUITAS SOLUÇÕES.</strong></p></div><div class="title-footer"><span>${c.saved?'Progresso local':'Progresso nesta sessão'}</span><strong>${xp(ms,c)} XP</strong></div>${c.legacy?'<p class="legacy-note">Nova bancada: suas campanhas anteriores foram preservadas.</p>':''}</main>`;}
export function campaign(ms:Mission[],c:Campaign):string{return `<main class="sector-screen"><p class="eyebrow">ESCOLHA UM SETOR</p><h1>Reconstrua o núcleo.</h1><div class="sector-map">${ms.map((m,i)=>`<button class="sector ${c.completed.includes(m.id)?'done':''}" data-action="select" data-index="${i}" ${i>c.completed.length?'disabled':''} aria-label="${i===5?'Desafio final':`Missão ${i+1}`}: ${m.title}"><span>${i===5?'◆':`0${i+1}`}</span><h2>${m.title}</h2><small>${m.concept}</small><b>${c.completed.includes(m.id)?'✓':i>c.completed.length?'▣':'▶'}</b></button>`).join('')}</div><button data-action="home">Menu principal</button></main>`;}
export function workspace(m:Mission,index:number,l:Layout,c:Case,state:CircuitState|undefined,selected:string,armed:Kind|null,connecting:string,moving:boolean,message:string,results:string[],caseIndex:number,paused:boolean):string{
 const n=l.nodes.find(n=>n.id===selected),count=l.nodes.length-m.fixed.length,busy=state?.status==='running'&&!paused;
 const hint=message||(connecting?'Escolha a peça que recebe este cabo.':moving?'Escolha um encaixe vazio.':armed?`Escolha um encaixe para a peça.`:n?'Escolha uma saída para conectar.':'Escolha uma peça ou arraste para a bancada.');
 return `<main class="bench-screen"><div class="mission-heading"><div><p class="eyebrow">${index===5?'NÚCLEO FINAL':`SETOR 0${index+1}`}</p><h1>${escape(m.title)}</h1></div><div class="mission-count"><strong>${count}/${m.budget}</strong><small>PEÇAS</small></div></div><div class="mission-goal"><span>◎</span><p>${escape(m.goal)}</p><button id="open-cases" data-action="cases" aria-label="Ver lotes e metas">${caseIndex+1}/${m.cases.length} ▦</button></div>${packets(m,c,state)}${board(m,l,state,selected,!!(armed||connecting||moving),c.target)}<div class="bench-feedback ${state?.status==='failed'?'error':''}" role="status" data-testid="feedback">${escape(state?.status==='failed'?state.message:busy?state?.message??'':hint)}</div><div class="bench-controls"><button id="run-circuit" class="primary" data-action="run">${busy?'Ⅱ Pausar':paused?'▶ Retomar':'▶ Ligar'}</button><button id="undo" data-action="undo" aria-label="Desfazer">↶</button><button id="help" data-action="help" aria-label="Ajuda">?</button><button id="open-log" data-action="log" aria-label="Registro da simulação">≡</button></div><div class="bench-dock">${n?inspector(m,n,connecting):palette(m,armed)}</div><div class="bench-bottom"><span>${results.filter(r=>r==='won').length}/${m.cases.length} lotes corretos</span><span>CONSTRUA SUA SOLUÇÃO</span></div></main>`;
}
export function result(m:Mission,earned:number,complete=false,used=0):string{const reference=Math.min(...m.solutions.map(l=>l.nodes.length-m.fixed.length)),stars=used<=reference?3:used===reference+1?2:1;return `<main class="result-screen"><div class="result-symbol">✓</div><p class="eyebrow">${complete?'NÚCLEO RECUPERADO':'CIRCUITO FUNCIONANDO'}</p><h1>${complete?'Você fez funcionar.':m.title}</h1><strong class="total-xp">${complete?'700':earned?`+${earned}`:'✓'} ${complete||earned?'XP':'Concluído'}</strong><p class="efficiency" aria-label="Eficiência opcional ${stars} de 3 estrelas">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</p><div class="result-actions"><button id="result-next" class="primary" data-action="next">${complete?'Ver missões':'Próximo setor →'}</button><button id="edit-circuit" data-action="edit">Experimentar outra montagem</button><button data-action="missions">Missões</button></div></main>`;}
export function modal(type:Overlay,m:Mission,l:Layout,selected:string,p:Preferences,state:CircuitState|undefined,caseIndex:number,results:string[]):string{
 if(!type)return '';
 let body='';
 if(type==='pause')body='<h2>Jogo pausado</h2><div class="modal-menu"><button id="resume" class="primary" data-action="resume">▶ Retomar</button><button data-action="restart">Reiniciar tentativa</button><button data-action="options">Opções</button><button data-action="missions">Missões</button><button data-action="home">Menu principal</button></div>';
 if(type==='options')body=`<h2>Opções</h2><label class="check-field"><input id="setting-reduced" type="checkbox" data-change="setting" data-key="reduced" ${p.reduced?'checked':''}> Movimento reduzido</label><label class="check-field"><input id="setting-large" type="checkbox" data-change="setting" data-key="largeText" ${p.largeText?'checked':''}> Texto maior</label><button id="reset-progress" data-action="reset-prompt">Reiniciar progresso</button>`;
 if(type==='new'||type==='reset')body='<h2>Começar de novo?</h2><p>Reinicia apenas esta campanha.</p><button id="reset-confirm" class="primary" data-action="confirm-reset">Confirmar</button>';
 if(type==='configure'){const n=l.nodes.find(n=>n.id===selected);body=n?configuration(m,n):'';}
 if(type==='help')body=`<h2>${m.concept}</h2><p>${escape(m.help)}</p><div class="mini-demo" aria-label="Exemplo: entrada passa por uma peça e chega à saída"><span>▸</span><i>→</i><strong>${m.mode==='connection'?'↗':m.mode==='transform'||m.mode==='final'?'+1':m.mode==='buffer'?'▤':'◇'}</strong><i>→</i><span>↥</span><b class="demo-dot"></b></div><ol><li>Escolha uma peça e um encaixe.</li><li>Selecione uma saída e o destino do cabo.</li><li>Ligue, observe e ajuste.</li></ol><p class="small-note">Cruzar cabos não cria conexão. Clique, toque ou teclado funcionam.</p>`;
 if(type==='cases')body=`<h2>Entradas e metas</h2><div class="case-list">${m.cases.map((c,i)=>`<button id="case-${i}" data-action="case" data-index="${i}" class="${i===caseIndex?'picked':''}">${results[i]==='won'?'✓':'○'} ${escape(c.label)}</button>`).join('')}</div><p class="small-note">A mesma montagem precisa resolver todos os lotes.</p>`;
 if(type==='log')body=`<h2>Registro real</h2><ol class="trace-list">${state?.trace.map(t=>`<li><strong>${escape(t.packet)}</strong> ${t.before} → ${t.after}<small>${escape(t.message)}</small></li>`).join('')||'<li>Ligue a bancada para observar os dados.</li>'}</ol>`;
 return `<dialog id="game-modal" aria-label="${type==='configure'?'Configurar peça':type==='help'?'Ajuda':type==='pause'?'Pausa':type==='log'?'Registro':type==='cases'?'Lotes':'Opções'}">${body}<button id="close-dialog" class="quiet" data-action="close-modal">${type==='configure'?'Pronto':'Voltar'}</button></dialog>`;
}
