import type {Mission,CaseResult} from '../core/arcade-engine';
import type {Sources} from '../core/workshop-save';
import {escape,robot} from './shared';
export const xp=(completed:string[])=>completed.length<=5?completed.length*100:700;
export function header(completed:string[],version:{version:string;sha:string}):string{return `<header class="topbar"><button class="brand" data-action="home" aria-label="Menu principal"><span>↱</span><strong>ROTA DO CÓDIGO<small>OFICINA DE JOGOS</small></strong></button><div class="top-meta"><span id="xp-count">${xp(completed)} XP</span><small>v${escape(version.version)} · ${escape(version.sha.slice(0,7))}</small></div></header>`;}
export function home(completed:string[],legacy:boolean,saved:boolean):string{return `<main class="home"><section class="home-copy"><span class="eyebrow">CONSTRUA ALGO QUE VOCÊ PODE JOGAR</span><h1>SEU CÓDIGO.<br>SEU <em>JOGO.</em></h1><p>Conserte a nave. Aprenda JavaScript.<br>Leve seu minijogo com você.</p><nav class="home-actions" aria-label="Menu do jogo"><button id="new-game" class="primary" data-action="new">＋ Começar oficina</button><button id="continue-game" data-action="continue" ${completed.length?'':'disabled'}>▶ Continuar</button><button id="missions-menu" data-action="missions">▦ Missões</button><button id="options" data-action="options">⚙ Opções</button></nav><small>${saved?'Progresso neste navegador':'Progresso somente nesta sessão'} · 5 missões + projeto final</small>${legacy?'<p class="legacy-note">Nova oficina: seu progresso anterior foi preservado.</p>':''}</section><div class="home-art" aria-hidden="true"><div class="orbit-ring"></div><div class="robot">${robot}</div><span class="floating-code">if (colisao) {<br>&nbsp;vidas -= 1;<br>}</span><div class="art-tag">01 → 05 → SEU JOGO</div></div></main>`;}
export function campaign(missions:Mission[],completed:string[]):string{return `<main class="campaign"><span class="eyebrow">OFICINA / PROGRESSO REAL</span><h1>Uma nave. Cinco consertos.</h1><div class="mission-list">${missions.map((m,i)=>`<button class="mission-card" data-action="select" data-index="${i}" ${i>completed.length?'disabled':''}><span class="mission-number">${completed.includes(m.id)?'✓':i===5?'★':`0${i+1}`}</span><strong>${escape(m.title)}<small>${escape(m.concept)}</small></strong><span>${i>completed.length?'🔒':'→'}</span></button>`).join('')}</div></main>`;}
export function workspace(missions:Mission[],index:number,tab:number,sources:Sources,tested:boolean,finalWon:boolean,summary:string):string{
 const m=missions[index],editing=missions[tab],source=sources[editing.functionName as keyof Sources];
 return `<main class="workshop"><div class="mission-heading"><div><span class="eyebrow">${index===5?'PROJETO FINAL':`MISSÃO 0${index+1}`} / ${escape(m.concept)}</span><h1 id="mission-title">${escape(m.title)}</h1><p>${escape(m.goal)}</p></div><button id="help" data-action="help" aria-label="Entender esta missão">?</button></div><div class="workshop-grid"><section class="play-column" aria-label="Minijogo real"><div id="player-host"></div><p id="run-message" class="run-message" role="status">Teste a regra no editor ou jogue para observar o problema.</p>${finalWon?'<div class="project-won"><strong>Seu jogo funciona!</strong><button id="download-game" class="primary" data-action="download">↓ Baixar meu jogo</button><small>HTML offline, com suas funções JavaScript.</small></div>':''}</section><section class="code-column" aria-label="Editor de JavaScript">${index===5?`<nav class="function-tabs" aria-label="Funções do projeto">${missions.slice(0,5).map((f,i)=>`<button data-action="tab" data-index="${i}" aria-pressed="${i===tab}">${['Teclas','Mover','Colisão','Pontos','Onda'][i]}</button>`).join('')}</nav>`:''}<div class="editor-window"><div class="editor-title"><span class="window-dots">● ● ●</span><strong>${escape(editing.functionName)}.js</strong><span>JS / INICIANTE</span></div><div class="editor-body"><div id="code-gutter" aria-hidden="true">${source.split('\n').map((_,i)=>`<span>${i+1}</span>`).join('')}</div><textarea id="code-editor" aria-label="Código da função ${escape(editing.functionName)}" spellcheck="false" autocapitalize="off" autocomplete="off" maxlength="6000">${escape(source)}</textarea></div><div class="editor-footer"><span>Altere a regra. Observe o resultado.</span><button id="reset-code" data-action="reset-code" aria-label="Restaurar código inicial">↶</button></div></div><div class="workshop-actions"><button id="test-rules" data-action="test" class="primary">✓ ${index===5?'Testar projeto':'Testar regra'}</button><button id="play-game" data-action="play">▶ Jogar</button></div><div class="test-feedback"><p id="test-summary" role="status" class="${tested?'passed':''}">${escape(summary||'Você pode experimentar antes de testar.')}</p><button id="show-tests" data-action="tests" aria-label="Ver situações de teste">↗ Ver testes</button></div><button id="next-mission" class="next-mission" data-action="next" ${tested&&index<5?'':'hidden'}>Próxima missão →</button></section></div></main>`;
}
export function caseTable(results:CaseResult[]):string{return results.length?`<div class="case-list">${results.map(c=>`<article class="case ${c.ok?'ok':'wrong'}"><strong>${c.ok?'✓':'×'} ${escape(c.label)}</strong><small>Entrada: ${escape(JSON.stringify(c.input))}</small><div>Esperado <code>${escape(JSON.stringify(c.expected))}</code> · Obtido <code>${escape(c.error||JSON.stringify(c.actual))}</code></div></article>`).join('')}</div>`:'<p>Use Testar regra para comparar sua função com todas as entradas.</p>';}
