import {describe,it,expect} from 'vitest';
import source from '../../src/content/missions.json';
import type {Mission,Layout,Config} from '../../src/core/circuit-types';
import {runCircuit,startCircuit,stepCircuit,decide} from '../../src/core/circuit-engine';
import {cablePath,defaultConfig,ports,validateLayout} from '../../src/core/circuit-layout';
const missions=source.missions as Mission[],copy=(i=0)=>structuredClone(missions[i]),mutate=(i:number,fn:(l:Layout)=>void)=>{const m=copy(i),l=m.solutions[0];fn(l);return runCircuit(m,m.cases[0],l);};
describe('montagens e dados reais',()=>{
 it.each(missions.map((m,i)=>[m.title,i] as const))('%s aceita duas soluções em todas entradas',(_,i)=>{const m=missions[i];for(const l of m.solutions)for(const c of m.cases)expect(runCircuit(m,c,l).status).toBe('won');});
 it('não modifica missão, entrada ou montagem',()=>{const m=copy(5),before=JSON.stringify(m);runCircuit(m,m.cases[0],m.solutions[0]);expect(JSON.stringify(m)).toBe(before);});
 it('cada tick retorna novo snapshot',()=>{const m=copy(),s=startCircuit(m,m.cases[0],m.solutions[0]),before=JSON.stringify(s);expect(stepCircuit(m,m.cases[0],m.solutions[0],s)).not.toBe(s);expect(JSON.stringify(s)).toBe(before);});
 it('estado final não volta a executar',()=>{const m=copy(),s=runCircuit(m,m.cases[0],m.solutions[0]);expect(stepCircuit(m,m.cases[0],m.solutions[0],s)).toBe(s);});
 it('×2 seguido de +2 engana na primeira entrada, mas falha na próxima',()=>{const m=copy(1),l=m.solutions[0];l.nodes.find(n=>n.id==='a')!.kind='multiply';l.nodes.find(n=>n.id==='a')!.config={value:2};l.nodes.find(n=>n.id==='b')!.config={value:2};const s=runCircuit(m,m.cases[0],l);expect(s.status).toBe('failed');expect(s.outputs.find(o=>o.id==='V1')?.value).toBe(4);expect(s.lastPacket?.id).toBe('V2');});
 it('alterar sensor manda corrompido ao destino errado',()=>{const s=mutate(2,l=>{l.nodes.find(n=>n.id==='a')!.config.a='permission';});expect(s.status).toBe('failed');expect(s.fault).toBe('ok');});
 it('trocar E por OU falha em credencial sem energia',()=>{const s=mutate(3,l=>{l.nodes.find(n=>n.id==='a')!.config.op='or';});expect(s.status).toBe('failed');});
 it.each(Array.from({length:8},(_,i)=>[!!(i&4),!!(i&2),!!(i&1)]))('E/OU credencial=%s energia=%s manutenção=%s',(credentials,energy,maintenance)=>{const config:Config={a:'credentials',b:'energy',op:'and',c:'maintenance',outer:'or',third:true};expect(decide(config,{...missions[3].cases[0].packets[0],credentials,energy,maintenance},{count:0,batchDone:false},missions[3].cases[0])).toBe((credentials&&energy)||maintenance);});
 it('sensores de estado distinguem antes/depois do lote',()=>{const c=missions[5].cases[0],p=c.packets[0];expect(decide({a:'countMet',b:'batchDone',op:'and'},p,{count:c.target,batchDone:false},c)).toBe(false);expect(decide({a:'countMet',b:'batchDone',op:'and'},p,{count:c.target,batchDone:true},c)).toBe(true);});
 it('agrupamento externo E e negação têm efeito real',()=>{const c=missions[3].cases[0],p={...c.packets[0],credentials:true,energy:false,maintenance:false};expect(decide({a:'credentials',b:'energy',op:'or',c:'maintenance',third:true,outer:'and',invert:true},p,{count:0,batchDone:false},c)).toBe(true);});
 it('buffer guarda antes de liberar e conta sem perder pacotes',()=>{const m=copy(4),c=m.cases[0],l=m.solutions[0];let s=startCircuit(m,c,l),held=false;while(s.status==='running'){s=stepCircuit(m,c,l,s);if(s.count&&!s.batchDone){held=true;expect(s.outputs.some(o=>o.sink==='ok')).toBe(false);}}expect(held).toBe(true);expect(s.count).toBe(2);expect(s.outputs).toHaveLength(4);});
 it('saída antecipada é rejeitada',()=>{const s=mutate(4,l=>{l.edges.find(e=>e.from==='a'&&e.port==='yes')!.to='ok';});expect(s.message).toMatch(/antes/);});
 it('memória zerada resolve lote sem íntegros',()=>{const m=copy(5),s=runCircuit(m,m.cases[2],m.solutions[0]);expect(s.status).toBe('won');expect(s.count).toBe(0);});
 it('final não aceita autorização sem integridade',()=>expect(mutate(5,l=>{l.nodes.find(n=>n.id==='a')!.config.op='or';}).status).toBe('failed'));
 it('cabo ausente localiza peça para correção',()=>{const s=mutate(0,l=>{l.edges.pop();});expect(s.message).toMatch(/Falta/);expect(s.fault).toBe('c');});
 it('buffer sem saída falha ao liberar lote',()=>expect(mutate(4,l=>{l.edges=l.edges.filter(e=>e.from!=='b');}).message).toMatch(/Buffer sem/));
 it('valor além de999 interrompe simulação',()=>{const m=copy(1),c=structuredClone(m.cases[0]);c.packets[0].value=999;expect(runCircuit(m,c,m.solutions[0]).message).toMatch(/999/);});
 it('orçamento de ticks protege execução',()=>{const m=copy(),s=startCircuit(m,m.cases[0],m.solutions[0]);s.tick=512;expect(stepCircuit(m,m.cases[0],m.solutions[0],s).message).toMatch(/512/);});
 it('fim exige conservação dos pacotes',()=>{const m=copy(),s=startCircuit(m,m.cases[0],m.solutions[0]);s.queue=[];s.batchDone=true;expect(stepCircuit(m,m.cases[0],m.solutions[0],s).message).toMatch(/destino/);});
 it('duplicação não é aceita',()=>{const m=copy(),s=startCircuit(m,m.cases[0],m.solutions[0]);s.queue=[{node:'ok',packet:m.cases[0].packets[0]}];s.outputs=[m.cases[0].expected[0]];expect(stepCircuit(m,m.cases[0],m.solutions[0],s).message).toMatch(/duplicou/);});
 it('buffer não reabre depois do fechamento',()=>{const m=copy(4),s=startCircuit(m,m.cases[0],m.solutions[0]);s.queue=[{node:'b',packet:m.cases[0].packets[0]}];s.batchDone=true;expect(stepCircuit(m,m.cases[0],m.solutions[0],s).message).toMatch(/depois/);});
 it('resultado alterado é diagnosticado na conferência final',()=>{const m=copy(),s=runCircuit(m,m.cases[0],m.solutions[0]);s.status='running';s.outputs[0].value=99;expect(stepCircuit(m,m.cases[0],m.solutions[0],s).status).toBe('failed');});
 it('meta da memória é conferida ao final',()=>{const m=copy(4),s=runCircuit(m,m.cases[0],m.solutions[0]);s.status='running';s.count=99;expect(stepCircuit(m,m.cases[0],m.solutions[0],s).message).toMatch(/Memória/);});
});
describe('montagem segura e espaço',()=>{
 it('cabo evita parede por trajeto ortogonal livre',()=>{const m=copy();expect(cablePath(m,m.fixed[0],{...m.fixed[1],x:2,y:0})).toBeNull();expect(cablePath(m,m.fixed[0],{...m.fixed[1],x:2,y:2})).not.toBeNull();});
 const bad:[string,(l:Layout)=>void,RegExp][]=[['IDs',l=>{l.nodes[2].id='in';},/duplicado/],['slot',l=>{l.nodes[2].x=0;l.nodes[2].y=2;},/encaixe/],['fora',l=>{l.nodes[2].x=7;},/fora/],['obstáculo',l=>{l.nodes[2].x=3;l.nodes[2].y=2;},/danificado/],['orientação',l=>{l.nodes[2].rotation=9;},/Orientação/],['fixo',l=>{l.nodes[0].rotation=1;},/fixo/],['ausente',l=>{l.nodes.shift();l.edges.shift();},/ausente/],['indisponível',l=>{l.nodes[2].kind='add';},/indisponível/],['endpoint',l=>{l.edges[0].to='none';},/ausente/],['porta',l=>{l.edges[0].port='yes';},/porta/],['entrada',l=>{l.edges[0].to='in';},/porta/],['saída repetida',l=>{l.edges.push({...l.edges[0]});},/Um|Uma/],['parede',l=>{l.edges[0].to='ok';},/alcance/]];
 it.each(bad)('%s rejeitado',(_,fn,pattern)=>expect(mutate(0,fn).message).toMatch(pattern));
 it('ciclo sem obstáculo também é rejeitado',()=>{const m=copy(1),l=m.solutions[0];l.edges.find(e=>e.from==='b')!.to='a';expect(validateLayout(m,l)).toMatch(/ciclo/);});
 it('orçamento de peças é público e bloqueante',()=>expect(mutate(1,l=>{l.nodes.push({id:'extra',kind:'relay',x:1,y:4,rotation:0,config:{}});}).message).toMatch(/limite/));
 it.each([0,4,1.5])('parâmetro%s inválido',value=>expect(mutate(1,l=>{l.nodes.find(n=>n.id==='a')!.config.value=value;}).message).toMatch(/1 a 3/));
 it('peça de soma não pode criar +3 fora da bandeja',()=>expect(mutate(1,l=>{l.nodes.find(n=>n.id==='a')!.config.value=3;}).message).toMatch(/Parâmetro/));
 it('sensor fora da missão é rejeitado',()=>expect(mutate(2,l=>{l.nodes.find(n=>n.id==='a')!.config.a='maintenance';}).message).toMatch(/Sensor/));
 it('regra incompleta é rejeitada',()=>expect(mutate(2,l=>{l.nodes.find(n=>n.id==='a')!.config={};}).message).toMatch(/incompleta/));
 it('padrões de nova peça são limitados ao conteúdo',()=>{expect(defaultConfig(missions[1],'add')).toEqual({value:1});expect(defaultConfig(missions[1],'multiply')).toEqual({value:2});expect(defaultConfig(missions[2],'filter').a).toBe('valid');expect(defaultConfig(missions[0],'relay')).toEqual({});});
 it('destino não expõe saída; sensor tem dois caminhos',()=>{expect(ports(missions[0].fixed[1])).toEqual([]);expect(ports(missions[2].solutions[0].nodes.at(-1)!)).toEqual(['yes','no']);});
});
