import {describe,it,expect} from 'vitest';
import data from '../../src/content/missions.json';
import {runLab,startLab,stepLab,evaluateExpression,validateProgram,countBlocks} from '../../src/core/lab-engine';
import type {Mission,Block,Action,Expr} from '../../src/core/lab-types';
const missions=data.missions as Mission[];
const a=(action:Action):Block=>({kind:'action',action});
const p=(name:'credentials'|'enoughEnergy'|'maintenance'):Expr=>({kind:'predicate',name});
describe('contratos do laboratório',()=>{
 for(const m of missions)for(const s of m.scenarios)it(`${m.mode}: solução vence em ${s.id}`,()=>expect(runLab(m,s,m.solution).status).toBe('won'));
 it('ler sensor desligado aponta dependência',()=>expect(runLab(missions[0],missions[0].scenarios[0],[a('read')]).message).toMatch(/sensor/i));
 it('iniciar sensor sem energia falha',()=>expect(runLab(missions[0],missions[0].scenarios[0],[a('sensor')]).status).toBe('failed'));
 it('enviar antes de ler falha',()=>expect(runLab(missions[0],missions[0].scenarios[0],[a('power'),a('sensor'),a('report')]).message).toMatch(/leitura/i));
 it('inicializar não basta para vencer',()=>expect(runLab(missions[0],missions[0].scenarios[0],[a('power')]).status).toBe('failed'));
 it('energia muda antes/depois e cenário permanece intacto',()=>{const s=missions[1].scenarios[0],initial=JSON.stringify(s);const before=startLab(missions[1],s,[a('charge'),a('process'),a('process')]);const next=stepLab(missions[1],s,before);expect(next.energy).toBe(s.energy+s.charge);expect(before.energy).toBe(s.energy);expect(next.trace[0].before.energy).toBe(s.energy);expect(JSON.stringify(s)).toBe(initial);});
 it('processar com energia insuficiente falha',()=>expect(runLab(missions[1],missions[1].scenarios[1],[a('process')]).message).toMatch(/energia/i));
 it('carga não pode ser repetida indefinidamente',()=>expect(runLab(missions[1],missions[1].scenarios[0],[a('charge'),a('charge')]).status).toBe('failed'));
 it('terceira operação excede objetivo',()=>expect(runLab(missions[1],{...missions[1].scenarios[0],energy:10},[a('process'),a('process'),a('process')]).status).toBe('failed'));
 it('contador exige inicialização',()=>expect(runLab(missions[4],missions[4].scenarios[0],[{kind:'foreach',body:[{kind:'if',condition:{kind:'predicate',name:'valid'},then:[{kind:'action',action:'send'},{kind:'action',action:'count'}],else:[{kind:'action',action:'review'}]}]}]).message).toMatch(/contador/i));
 it('encaminhar todos ignora casos corrompidos',()=>expect(runLab(missions[2],missions[2].scenarios[1],[a('send')]).status).toBe('failed'));
 it('contar antes de enviar é inválido',()=>expect(runLab(missions[4],missions[4].scenarios[0],[a('resetCount'),{kind:'foreach',body:[{kind:'action',action:'count'}]}]).status).toBe('failed'));
 it('não pode contar pacote duas vezes',()=>{const bad=structuredClone(missions[4].solution);const loop=bad.find(b=>b.kind==='foreach');if(loop?.kind==='foreach'){const rule=loop.body.find(b=>b.kind==='if');if(rule?.kind==='if')rule.then.push({kind:'action',action:'count'});}expect(runLab(missions[4],missions[4].scenarios[0],bad).status).toBe('failed');});
 it('processar lote sem contador não vence',()=>expect(runLab(missions[4],missions[4].scenarios[0],[{kind:'foreach',body:[{kind:'if',condition:{kind:'predicate',name:'valid'},then:[{kind:'action',action:'send'}],else:[{kind:'action',action:'review'}]}]}]).status).toBe('failed'));
 it('relatório final exige central ligada',()=>expect(runLab(missions[5],missions[5].scenarios[0],missions[5].solution.slice(1)).message).toMatch(/central/i));
 it('liberar antes do lote terminar falha',()=>expect(runLab(missions[5],missions[5].scenarios[0],[a('power'),a('resetCount'),a('release')]).status).toBe('failed'));
 it('nenhuma liberação não vence final, mesmo com contador correto',()=>expect(runLab(missions[5],missions[5].scenarios[0],missions[5].solution.slice(0,-1)).status).toBe('failed'));
 it('liberação sem regra explícita não comprova decisão final',()=>expect(runLab(missions[5],missions[5].scenarios[0],[...missions[5].solution.slice(0,-1),a('release')]).message).toMatch(/condição/i));
 it('OU no relatório é inseguro quando uma condição falta',()=>{const program=structuredClone(missions[5].solution);const last=program.at(-1);if(last?.kind==='if'&&last.condition.kind!=='predicate')last.condition.kind='or';expect(runLab(missions[5],missions[5].scenarios[0],program).status).toBe('failed');});
 it('orçamento interrompe programa excessivo',()=>{const m={...missions[0],maxBlocks:120};expect(runLab(m,m.scenarios[0],Array.from({length:110},()=>a('power'))).message).toMatch(/100/);});
 it('estado final não executa de novo',()=>{const m=missions[0],s=m.scenarios[0],done=runLab(m,s,m.solution);expect(stepLab(m,s,done)).toBe(done);});
 it('ação não disponível é rejeitada',()=>expect(()=>validateProgram(missions[0],[a('send')])).toThrow(/disponível/i));
 it('programa vazio é rejeitado',()=>expect(()=>validateProgram(missions[0],[])).toThrow(/bloco/i));
 it('limite de blocos inclui os ramos',()=>expect(countBlocks(missions[5].solution)).toBe(10));
 it('limite de blocos é obrigatório',()=>expect(()=>validateProgram({...missions[0],maxBlocks:1},missions[0].solution)).toThrow(/limite/i));
 it('laço aninhado é rejeitado em runtime',()=>expect(()=>validateProgram(missions[4],[{kind:'foreach',body:[{kind:'foreach',body:[]}]}] as unknown as Block[])).toThrow(/aninhad/i));
 it('condição sem pacote aponta contexto inválido',()=>expect(runLab(missions[4],missions[4].scenarios[0],[{kind:'if',condition:{kind:'predicate',name:'valid'},then:[{kind:'action',action:'send'}],else:[{kind:'action',action:'review'}]}]).message).toMatch(/pacote/i));
 for(const credentials of [false,true])for(const energy of [0,3])for(const maintenance of [false,true])it(`E/OU: ${+credentials},${energy},${+maintenance}`,()=>{const m=missions[3],s={...m.scenarios[0],credentials,energy,maintenance};const e:Expr={kind:'or',left:{kind:'and',left:p('credentials'),right:p('enoughEnergy')},right:p('maintenance')};expect(evaluateExpression(e,startLab(m,s,m.solution),s)).toBe((credentials&&energy>=3)||maintenance);});
 it('condição desconhecida rejeita, sem código arbitrário',()=>expect(()=>validateProgram(missions[3],[{kind:'if',condition:{kind:'predicate',name:'eval'},then:[],else:[]}] as unknown as Block[])).toThrow(/condição/i));
 it('fila e traço de execução são imutáveis entre passos',()=>{const m=missions[5],s=m.scenarios[0],prev=startLab(m,s,m.solution),copy=JSON.stringify(prev);stepLab(m,s,prev);expect(JSON.stringify(prev)).toBe(copy);});
});
